version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ops/Dockerfile.backend
    env_file:
      - .env.example
    volumes:
      - ./data:/app/data:ro
    ports:
      - "8000:${BACKEND_PORT:-8000}"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ops/Dockerfile.frontend
    env_file:
      - .env.example
    ports:
      - "5173:${FRONTEND_PORT:-5173}"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped